import { HospitalUnity } from "./hospital-unity";
import { Professional } from "./professional";
import { Report } from "./report";

export interface PatientRequest {
    id: number,
    report_id: number,
    medical_professional_id: number,
    social_professional_id?: number,
    travel_professional_id?: number,
    owner_professional_id: number,
    cost_assistance_professional_id?: number,
    accountability_professional_id?: number,
    payment_professional_id?: number,
    type: string,
    consultation_date: string,
    observation: string,
    report?: Report,
    medical_professional?: Professional,
    social_professional?: Professional,
    travel_professional?: Professional,
    owner_professional?: Professional,
    cost_assistance_professional?: Professional,
    accountability_professional?: Professional,
    payment_professional?: Professional,
    hospital_unity: HospitalUnity,
    status: boolean,
    medical_status: boolean,
    social_status:boolean,
    travel_status: boolean,
    cost_assistance_status: boolean,
    accountability_status: boolean,
    back_to_owner: string | null,
    is_owner_archive: boolean,
    back_to_medical: string | null,
    is_medical_archive: boolean,
    back_to_social: string | null,
    is_social_archive: boolean,
    back_to_travel: string | null,
    is_travel_archive: boolean,
    back_to_cost_assistance: string | null,
    is_cost_assistance_archive: boolean,
    back_to_accountability: string | null,
    is_accountability_archive: boolean,
    back_to_payment: string | null,
    is_payment_archive: boolean,
    created_at: any,
    attachments: any,
    opinions: any,
    cost_assistances: any,
    accountabilities: any,
}
